### ISSUE TITLE
PaperMC 1.21 バージョンアップ

### ISSUE THREAD

**Issue by zztkm** [pistachiostudio/genkai-mc-server#108]
Minecraft 1.21 で遊べるようにすることを最優先にするために、動かないプラグインは一旦外す方向でいく。

Tasks

- [x] Paper MC の 1.21 初期対応（動かないプラグインは外す
- [ ] PaperMC の 1.21 正式対応
  - [ ] PAPER_CHANNEL 環境変数なしでビルドできる
- [x] WorldGuard の 1.21 対応 (World Edit も
- [x] Dynmap
- [ ] Hidden Armor 1.21 対応（自分でがんばらないとだめかも？

memo
- 荒らし対策プラグインが動かないため、一旦ホワイトリスト形式を継続し、荒らし対策が追いついたら公開状態に変更する。
- それまでこの issue はトラッキング用として残しておく

**Comment by zztkm** [comment]
VERSION を 1.21 に変更してみたが、以下のエラーが発生し、起動に失敗した。

```bash
paper  | 2024-06-19T12:49:16.802196843Z [init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 2 1000 1000 4096 Jun 19 12:47 /data'
paper  | 2024-06-19T12:49:16.806177943Z [init] Starting RCON commands
paper  | 2024-06-19T12:49:16.808055243Z [init] Rcon cmds functionality enabled
paper  | 2024-06-19T12:49:16.808940543Z [init] Resolving type given PAPER
paper  | 2024-06-19T12:49:19.165129550Z [mc-image-helper] 12:49:19.163 ERROR : Invalid parameter provided for 'install-paper' command: No build found for version 1.21 with channel default
paper  | 2024-06-19T12:49:19.487965451Z [init] ERROR: failed to download paper
```

**Comment by zztkm** [comment]
WorldGuard 死んでそう。

```bash
paper  | 2024-06-19T13:01:24.482015825Z [13:01:24 ERROR]: Could not pass event BlockFromToEvent to WorldGuard v7.0.10+d9424b1
paper  | 2024-06-19T13:01:24.482024625Z java.lang.NoClassDefFoundError: Could not initialize class com.sk89q.worldguard.bukkit.util.Materials
paper  | 2024-06-19T13:01:24.482027025Z         at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.listener.WorldGuardBlockListener.onBlockFromTo(WorldGuardBlockListener.java:114) ~[worldguard-bukkit-7.0.10-dist.jar:?]
paper  | 2024-06-19T13:01:24.482028925Z         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor80.execute(Unknown Source) ~[?:?]
paper  | 2024-06-19T13:01:24.482030325Z         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
paper  | 2024-06-19T13:01:24.482032025Z         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482033725Z         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
paper  | 2024-06-19T13:01:24.482035325Z         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482036925Z         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482038425Z         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
paper  | 2024-06-19T13:01:24.482046325Z         at net.minecraft.world.level.material.FlowingFluid.spreadToSides(FlowingFluid.java:186) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482048125Z         at net.minecraft.world.level.material.FlowingFluid.spread(FlowingFluid.java:157) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482049625Z         at net.minecraft.world.level.material.FlowingFluid.tick(FlowingFluid.java:502) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482051125Z         at net.minecraft.world.level.material.FluidState.tick(FluidState.java:78) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482052625Z         at net.minecraft.server.level.ServerLevel.tickFluid(ServerLevel.java:1148) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482054125Z         at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:192) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482055625Z         at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:89) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482058025Z         at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:674) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482059625Z         at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1733) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482061125Z         at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:471) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482062625Z         at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482064025Z         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482065825Z         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-9-4ea696f]
paper  | 2024-06-19T13:01:24.482067425Z         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
paper  | 2024-06-19T13:01:24.482068925Z Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.Tag does not have member field 'org.bukkit.Tag ITEMS_MUSIC_DISCS' [in thread "Server thread"]
paper  | 2024-06-19T13:01:24.482070725Z         at worldguard-bukkit-7.0.10-dist.jar/com.sk89q.worldguard.bukkit.util.Materials.<clinit>(Materials.java:867) ~[worldguard-bukkit-7.0.10-dist.jar:?]
paper  | 2024-06-19T13:01:24.482072425Z         ... 22 more
``

**Comment by zztkm** [comment]
Dynmap もだめそう。

**Comment by zztkm** [comment]
WorldEdit のテスト版に 1.21 対応が来てる 👀 

https://builds.enginehub.org/job/worldedit

これが落ち着いたら、次は WorldGuard がくるはず

**Comment by zztkm** [comment]
荒らし対策プラグインの導入と利用方法のドキュメント化を正式に進める。

まずは fukakoro さんに OP 権限を渡す
